#!/usr/bin/env bun
/**
 * Emit seed SQL for the `designs` table from the bundled templates.
 *
 * Usage:
 *   bun --cwd worker run seed > /tmp/seed.sql
 *   bun worker/scripts/seed.ts --only=vital-signs,neon-pulse > /tmp/new.sql
 *
 * With `--only=<id1,id2,...>` only the named templates are emitted, so a
 * maintainer can ship new additions without re-inserting the original seed
 * rows. Invoke the script directly (not via `bun run seed`) so `--only`
 * reaches the script instead of being consumed by `bun run`. Template ids
 * match the `id` field in TEMPLATES (e.g. "vital-signs").
 *
 * The output uses `INSERT OR IGNORE`, so reapplying is safe — primary-key
 * collisions are silently skipped. Slugs include a random suffix so re-runs
 * produce fresh rows (the UNIQUE constraint on slug only fires on exact
 * duplicates, which the suffix prevents).
 *
 * Pure stdout emission; does no network or filesystem I/O.
 */

import { TEMPLATES } from "@statusline/shared/templates";
import { customAlphabet } from "nanoid";

const nanoid = customAlphabet(
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-",
  10,
);

// Mirrors `kebabCase` in worker/src/designs.ts so seed slugs are shaped
// identically to slugs produced by the publish handler.
function kebabCase(s: string): string {
  return (
    s
      .normalize("NFKD")
      .replace(/[^\w\s-]/g, "")
      .trim()
      .replace(/[\s_]+/g, "-")
      .replace(/-+/g, "-")
      .toLowerCase()
      .replace(/^-+|-+$/g, "") || "design"
  );
}

// SQLite uses doubled single-quotes for escaping inside string literals.
function sqlEscape(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const SEED_AUTHOR = "Statusline Maker";
const now = Date.now();

// Parse `--only=a,b,c` out of argv. Anything else is ignored so future flags
// can be added without breaking the existing `bun run seed > file.sql` flow.
const onlyArg = process.argv.find((a) => a.startsWith("--only="));
const onlySet = onlyArg
  ? new Set(
      onlyArg
        .slice("--only=".length)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    )
  : null;

if (onlySet) {
  const known = new Set(TEMPLATES.map((t) => t.id));
  const unknown = [...onlySet].filter((id) => !known.has(id));
  if (unknown.length > 0) {
    console.error(`seed.ts: unknown template id(s): ${unknown.join(", ")}`);
    process.exit(1);
  }
}

const selected = onlySet
  ? TEMPLATES.filter((t) => onlySet.has(t.id))
  : TEMPLATES;

const stmts: string[] = [];
stmts.push("-- Auto-generated by worker/scripts/seed.ts. Do not edit by hand.");
if (onlySet) {
  stmts.push(`-- Filtered to: ${[...onlySet].join(", ")}`);
}
// D1 `wrangler d1 execute --remote` rejects explicit BEGIN/COMMIT — the API
// wraps the batch in its own transaction. Emit plain INSERTs.

for (const tpl of selected) {
  const id = nanoid();
  const slug = `${kebabCase(tpl.name)}-${id.slice(0, 4)}`;
  // Store only the Design payload in the `json` column — the publish handler
  // does the same; metadata like name/description live in their own columns.
  const json = JSON.stringify(tpl.design);
  stmts.push(
    `INSERT OR IGNORE INTO designs (id, json, slug, name, author_name, description, forked_from, published_at, views, forks, installs) VALUES (` +
      [
        sqlEscape(id),
        sqlEscape(json),
        sqlEscape(slug),
        sqlEscape(tpl.name),
        sqlEscape(SEED_AUTHOR),
        sqlEscape(tpl.description),
        "NULL",
        String(now),
        "0",
        "0",
        "0",
      ].join(", ") +
      ");",
  );
}

console.log(stmts.join("\n"));
