#!/usr/bin/env bun
/**
 * Emit seed SQL for the `designs` table from the bundled templates.
 *
 * Usage:
 *   bun --cwd worker run seed > /tmp/seed.sql
 *
 * The output is a single transaction of `INSERT OR IGNORE` statements, so it
 * is safe to re-apply against an existing DB — slug collisions are silently
 * skipped rather than erroring out.
 *
 * Pure stdout emission; does no network or filesystem I/O.
 */

import { TEMPLATES } from "@statusline/shared/templates";
import { customAlphabet } from "nanoid";

const nanoid = customAlphabet(
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-",
  10,
);

// Mirrors `kebabCase` in worker/src/designs.ts so seed slugs are shaped
// identically to slugs produced by the publish handler.
function kebabCase(s: string): string {
  return (
    s
      .normalize("NFKD")
      .replace(/[^\w\s-]/g, "")
      .trim()
      .replace(/[\s_]+/g, "-")
      .replace(/-+/g, "-")
      .toLowerCase()
      .replace(/^-+|-+$/g, "") || "design"
  );
}

// SQLite uses doubled single-quotes for escaping inside string literals.
function sqlEscape(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const SEED_AUTHOR = "Statusline Maker";
const now = Date.now();

const stmts: string[] = [];
stmts.push("-- Auto-generated by worker/scripts/seed.ts. Do not edit by hand.");
// D1 `wrangler d1 execute --remote` rejects explicit BEGIN/COMMIT — the API
// wraps the batch in its own transaction. Emit plain INSERTs.

for (const tpl of TEMPLATES) {
  const id = nanoid();
  const slug = `${kebabCase(tpl.name)}-${id.slice(0, 4)}`;
  // Store only the Design payload in the `json` column — the publish handler
  // does the same; metadata like name/description live in their own columns.
  const json = JSON.stringify(tpl.design);
  stmts.push(
    `INSERT OR IGNORE INTO designs (id, json, slug, name, author_name, description, forked_from, published_at, views, forks) VALUES (` +
      [
        sqlEscape(id),
        sqlEscape(json),
        sqlEscape(slug),
        sqlEscape(tpl.name),
        sqlEscape(SEED_AUTHOR),
        sqlEscape(tpl.description),
        "NULL",
        String(now),
        "0",
        "0",
      ].join(", ") +
      ");",
  );
}

console.log(stmts.join("\n"));
